default: &default
adapter: redis
url: redis://localhost:6379/1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  url: 'redis://rediscloud:1qhrfaECnHUmkXQx@redis-14288.c3.eu-west-1-1.ec2.cloud.redislabs.com:14288'
