meta_product_name: "Happynvestor"
meta_title: "Happynvestor - Devenez investisseur, simplement"
meta_description: "Quelques clics suffisent pour trouver la meilleure offre"
meta_image: "Gatsby_House.jpg"                           # Une image dans votre dossier app/assets/images/
