meta_product_name: "Happynvestor"
meta_title: "Happynvestor - Devenez investisseur, simplement"
meta_description: "Quelques clics suffisent pour trouver la meilleure offre"
meta_image: "http://cbsnews1.cbsistatic.com/hub/i/r/2011/04/17/9ded2b2f-a644-11e2-a3f0-029118418759/thumbnail/1200x630/44a2f13f942254aab931a3b37c4d30f3/Gatsby_House.jpg"                           # Une image dans votre dossier app/assets/images/
